apiVersion: v2
type: application
appVersion: v1.61.1
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.8.18
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~10.3.17
    condition: postgresql.enabled
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Upgrade to 1.61.1
    - "We have just published a security release of Synapse (1.61.1), which fixes a vulnerability with URL previews. Administrators of Synapse instances are encouraged to update ASAP!"
    - "https://matrix.org/blog/2022/06/28/security-release-synapse-1-61-1"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: synapse
      image: matrixdotorg/synapse:v1.61.1
