apiVersion: v2
type: application
appVersion: v1.40.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.7.45
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Update to latest synapse version.
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: synapse
      image: matrixdotorg/synapse:v1.40.0
