apiVersion: v2
type: application
appVersion: v1.75.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.8.25
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~10.16.2
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ~17.2.0
    condition: redis.enabled
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Upgrade to 1.75.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: synapse
      image: matrixdotorg/synapse:v1.75.0
