apiVersion: v2
appVersion: v1.80.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.19.0
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~12.3.0
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ~17.10.0
    condition: redis.enabled
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update matrixdotorg/synapse docker tag to v1.86.0 ([ac5d0f1](https://github.com/halkeye-helm-charts/synapse/commit/ac5d0f116ad7fa70f7558b3fb0deb18921b86a7e))"
  artifacthub.io/images: |
    - name: synapse
      image: "matrixdotorg/synapse:v1.86.0"
