apiVersion: v2
type: application
appVersion: v1.30.1
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.7.35
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Bump app version to 1.30.1 which handles a openssl security issue - https://github.com/matrix-org/synapse/releases/tag/v1.30.1
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: synapse
      image: matrixdotorg/synapse:v1.30.1
