apiVersion: v2
appVersion: "v1.80.0"
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.8.27
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~12.2.6
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ~17.2.0
    condition: redis.enabled
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "force release ([0bb806d](https://github.com/halkeye-helm-charts/synapse/commit/0bb806d5121e9ceae35d065c15f74733cd898acf))"
  artifacthub.io/images: |
    - name: synapse
      image: "matrixdotorg/synapse:v1.80.0"
