apiVersion: v1
appVersion: v1.24.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.7.24
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
