apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
{{ include "synapse.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9092
      targetPort: worker-tcp
      protocol: TCP
      name: worker-tcp
    - port: 9093
      targetPort: worker-http
      protocol: TCP
      name: worker-http
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
